# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
    DATABASE_URL: mysql://root:@localhost:3306/chat

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        name:
        - MySql 5.7

        include:
        - name: Node.js 16.x
          node-version: "16.13"
          docker-mysql-type: mysql
          docker-mysql-version: "5.7"


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup environment
      shell: bash
      run: |
        echo "MYSQL_DATABASE=chat" >> "$GITHUB_ENV"
        echo "MYSQL_HOST=localhost" >> "$GITHUB_ENV"
        echo "MYSQL_PORT=3306" >> "$GITHUB_ENV"
        echo "MYSQL_USER=root" >> "$GITHUB_ENV"

    - name: Install MySQL
      run: docker run -d --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=$MYSQL_DATABASE -p $MYSQL_PORT:3306 $DOCKER_MYSQL_TYPE:$DOCKER_MYSQL_VERSION
      env:
        DOCKER_MYSQL_TYPE: mysql
        DOCKER_MYSQL_VERSION: "5.7"



    - name: Install dependencies
      run: npm i

    - name: create database
      run: npx prisma db push


    - name: Deploy application
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "chat-in-realitime"
        heroku_email: "rodrigobrinate32@gmail.com"
        # set buildpacks